config/routes.rb
Rails.application.routes.draw do
  root  'main#index'
  
  post  'subscribe'   =>  'main#subscribe',    as: 'subscribe' 
  get   'success'     =>  'main#success'  ,    as: 'success'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :subscribe

    ## Root Path
    def index
        @subscriber = Subscriber.new
    end

    ## POST /subscribe
    def subscribe
        @subscribers = Subscriber.all
        @subscriber = Subscriber.new(subscriber_params)

        @subscriber.email = @subscriber.email.strip
        @subscriber.save! unless @subscribers.find_by_email(@subscriber.email).present?

        redirect_to success_path(email: @subscriber.email)
    end

    ## GET /thank-you
    def success; end

    ## Subscriber Parameters
    private
    def subscriber_params
        params.require(:subscriber).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Title -->
    <title><%= content_for?(:title) ? yield(:title) : "Raffles but awesome! - Parapol" %></title>

    <!-- Viewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- CSRF and CSP Meta Tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Generic Meta Tags -->
    <meta name="keywords" content="raffle, lottery, parapol, awesome">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Host, manage, and join raffles in the coolest way possible with Parapol.' %>">
    
    <!-- Open Graph -->
    <meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'Raffles but awesome! - Parapol' %>">
    <meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : 'Host, manage, and join raffles in the coolest way possible with Parapol.' %>"/>
    <meta property="og:image" content="<%= content_for?(:image) ? yield(:image) : 'https://parapol-waitlist.herokuapp.com/og-image.png' %>"/>
    <meta property="og:type" content='website'/>
    <meta property="og:url" content='<%= request.original_url %>'/>

    <!-- Theme Color -->
    <meta name="theme-color" content="#a83232">
    <meta name="msapplication-TileColor" content="#a83232">

    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="57x57" href="/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
    <meta name="msapplication-TileImage" content="/icons/ms-icon-144x144.png">

    <!-- Manifest -->
    <link rel="manifest" href="/manifest.json">

    <!-- Stylesheets -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '/fontawesome/web/css/all.css', media: 'all', 'data-turbolinks-track' => 'reload' %>

    <!-- Javascript -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZEEDTH4FJD"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-ZEEDTH4FJD');
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<!-- Page Background -->
<div id="page-background"></div>

<!-- Particles -->
<div id="particles"></div>

<!-- Landing Page -->
<div id="landing-page" class="page">
  <%= render 'components/nav' %>
  
  <!-- HERO SECTION -->
  <main id="hero">
    <div id="hero-text">
      <h2 class="header glow-text"><strong>Raffles but awesome!</strong></h2>
      <h4 class="sub-header">Host, manage, and join raffles the cool way.</h4>
    </div>
    
    <div id="subscribe">
      <%= form_with(model: @subscriber, url: subscribe_path, method: :post) do |form| %>
        <div id="email-field">
          <%= form.email_field :email, placeholder: "Enter your email", autocomplete: 'email', required: true %>
        </div>
        <%= form.submit "Join waitlist", data: { disable_with: "Loading..." }, class: "cta" %>
      <% end %>
    </div>
    <p id="subscribe-prompt"><span>COMING SOON:</span> Sign up to get notified as soon as we launch.</p>
    
    <img src="/images/ticket.png" id="hero-img" class="float"/>
  </main>

  <br><br>
  <section id="about-us" class="section-width-limit">
    <p id="hook">Luck alone won't cut it.<br>Be lucky and awesome at the same time!</p>

    <img src="/images/cool-emoji.png" class="float"/>

    <p id="value-proposition">
      <i>
        Whether you're setting up or joining a raffle, parapol will help you do it the coolest way possible.
      </i>
    </p>
  </section>

  <br><br>
  <section id="learn-more" class="section-width-limit">
    <p id="learn-more-prompt" class="prompt">Learn More</p>
    <div class="section-bridge"></div>

    <div id="details">
      <h2 class="header">Parapol</h2>
      <p class="sub-header">All-in-one platform for raffles.</p>
      <div class="card-list">
          <div class="card-list-item">
              <div class="label">
                  <p class="title">For Organizers</p>
              </div>
              <div class="card">
                  <p class="body">
                    <strong>Set-up a raffle within 5 minutes</strong> and provide people with an easier way to join your raffle to get more participants.<br><br>
                    <span class="bullet">🤖</span> <strong>Automated</strong> issuance of tickets & tracking of payments + receipts.<br><br>
                    <span class="bullet">📃</span> <strong>Eliminate</strong> the need for inconvenient online forms.<br><br>
                    <span class="bullet">📈</span> <strong>Monitor</strong> your raffles with visual tables and graphs.<br><br>
                    <span class="bullet">🔔</span> <strong>Send</strong> notifications to your participants. (for draw dates, results, etc.)<br><br>
                    <span class="bullet">🎰</span> <strong>Host and perform</strong> the raffle draws through your own dashboard.<br><br>
                  </p>
              </div>
          </div>
          <div class="card-list-item">
              <div class="label">
                  <p class="title">For Participants</p>
              </div>
              <div class="card">
                  <p class="body">
                    <strong>Join a raffle in less than 30 seconds</strong> and get your tickets instantly.<br><br>
                    <span class="bullet">🔎</span> <strong>Discover</strong> hundreds of awesome raffles you can join.<br><br>
                    <span class="bullet">💵</span> <strong>Buy and pay</strong> for your tickets directly and securely.<br><br>
                    <span class="bullet">👌</span> <strong>Feel safe</strong> as all raffles at parapol undergoes verification.<br><br>
                    <span class="bullet">💼</span> <strong>Get protected</strong> with our Parapol Guarantee.<br><br>
                    <span class="bullet">📧</span> <strong>Stay updated</strong> with draw dates, results, etc. through email and push notifications.<br><br>
                  </p>
              </div>
          </div>
  </section>

  <br><br><br><br>
  <section id="contact-us" class="section-width-limit">
    <div class="card gradient light-shadow">
      <h2 class="title">Have any questions?</h2>
      <a href="https://m.me/parapolPH" target="_blank" class="cta dark-shadow">Message us</a>
    </div>
  </section>

  <br>
  <%= render 'components/footer' %>
</div>

<!-- Particles Script -->
<script type="text/javascript">
  if (typeof(indexParticlesJS) === "undefined") {
    const indexParticlesJS = window.particlesJS;
    indexParticlesJS.load('particles', 'particles.json');
  } else {
  	indexParticlesJS.load('particles', 'particles.json');
  }
</script>

<!-- Typeform Script -->
<script src="//embed.typeform.com/next/embed.js"></script>

app/views/main/success.html.erb
<!-- Page Background -->
<div id="page-background"></div>

<!-- Particles -->
<div id="particles" style="opacity: 0.42;"></div>

<!-- Success Page -->
<div id="success-page" class="page">
  <%= render 'components/nav' %>

  <main>
    <br><br>
    <div id="banner">
      <h2 class="header">Thank you!</h2>
      <h4 class="sub-header">We have added your email address to our waitlist.</h4>
      <p class="subscriber-count card light-shadow"><%= Subscriber.count %> people are waiting with you</p>
      <p class="subscription-note">This subscription is held for <%= params[:email].strip %>. Is this <%= link_to "not you?", root_path %>
    </div>

    <br><br><br><br><br>
    <div class="section-bridge"></div>
    <div id="invite">
      <h2 class="header">Invite Friends</h2>
      <p class="invite-prompt">Invite your friends who might be interested to host or join raffles!</p>
      <div id="channels">
        <a href="fb-messenger://share/?link=https%3A%2F%2Fwww.parapol.ph" target="_blank" id="messenger" class="cta dark-shadow no-underline">
          <i class="fab fa-facebook-messenger"></i> Send in Messenger
        </a>
        <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.parapol.ph" target="_blank" id="facebook" class="cta dark-shadow no-underline">
          <i class="fab fa-facebook"></i> Post to Facebook
        </a>
        <a href="http://www.twitter.com/share?url=https%3A%2F%2Fwww.parapol.ph" target="_blank" id="twitter" class="cta dark-shadow no-underline">
          <i class="fab fa-twitter"></i> Tweet
        </a>
      </div>
    </div>
    
    <br><br><br><br><br>
  </main>
</div>
<!-- Particles Script -->
<script type="text/javascript">
  if (typeof(successParticlesJS) === "undefined") {
	const successParticlesJS = window.particlesJS;
	successParticlesJS.load('particles', 'particles.json');
  } else {
  	successParticlesJS.load('particles', 'particles.json');
  }
</script>